project_name: hello-world

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - binary: hello-world
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/trnubo/go-hello-world/cmd.Version={{.Version}} -X github.com/trnubo/go-hello-world/cmd.Commit={{.FullCommit}} -X github.com/trnubo/go-hello-world/cmd.Date={{.Date}}
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      # freebsd/arm64 added in golang 1.14
      - goos: freebsd
        goarch: arm64

snapshot:
  name_template: "git-{{.ShortCommit}}"

archives:
  - format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "trnubo/hello-world:{{ .Major }}"
      - "trnubo/hello-world:{{ .Major }}.{{ .Minor }}"
      - "trnubo/hello-world:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "trnubo/hello-world:latest"
    skip_push: true

release:
  github:
    owner: trnubo
    name: go-hello-world
  disable: true
